### PR TITLE
Fix issue with arrays containing null values

### LINKED ISSUE #10: Version 1.4.0 breaks when extra contains is null or undefined
I'm using react-bem-helper passing down the className from props as an extra like this:

```
bem({
      modifiers: {...},
      extra: [
        status,
        className,
      ],
    })
```

Since version 1.4.0 it breaks when className is null/undefined with the following error message:

```
TypeError: Cannot read property 'split' of undefined
      at stringToArray (node_modules/react-bem-helper/index.js:21:16)
      at node_modules/react-bem-helper/index.js:48:27
      at Array.reduce (native)
      at listToArray (node_modules/react-bem-helper/index.js:47:17)
      at node_modules/react-bem-helper/index.js:102:29
```

### PR DESCRIPTION
**Pull request by AlexanderOtavka**
Fixes #10.

Also adds a test so this doesn't happen again.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -44,9 +44,13 @@ function listToArray(list) {
...
-    return list.reduce(function (array, string) {
-      return array.concat(stringToArray(string));
-    }, []);
+    return list
+      .filter(function (string) {
+        return !!string;
+      })
+      .reduce(function (array, string) {
+        return array.concat(stringToArray(string));
+      }, []);
```
Comment (marcohamersma) [inline index.js:53]: I guess we can combine this by doing:
```js
.reduce(function (array, string) {
  return !!string ? array.concat(stringToArray(string)) : array;
}, []);
```

**Comment by marcohamersma** [comment]
Ah yes, thanks 👍  Was about to do that myself :)

File: index.js (hunk 1 above)
Comment (AlexanderOtavka) [reply index.js:53]: While that would be more concise, I think having it in two steps is easier to understand.
